<?php
/**
 * ELITE UNIQUE FEATURE: Interview Scheduler
 * JobPortal Theme - Calendar Integration & Automated Scheduling
 *
 * @package JobPortal
 * @version 2.0.0 ELITE
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Interview Scheduler Shortcode
 * Usage: [jobportal_interview_scheduler]
 */
function jobportal_interview_scheduler_shortcode() {
    ob_start();
    ?>
    <div class="jp-interview-scheduler">

        <div class="jp-scheduler-header">
            <h2><?php esc_html_e('Schedule Your Interview', 'jobportal'); ?></h2>
            <p><?php esc_html_e('Select a convenient time slot for your interview', 'jobportal'); ?></p>
        </div>

        <div class="jp-scheduler-container">

            <!-- Calendar Section -->
            <div class="jp-scheduler-calendar">

                <div class="jp-calendar-header">
                    <button class="jp-cal-nav" id="prev-month">&larr;</button>
                    <h3 id="current-month">March 2024</h3>
                    <button class="jp-cal-nav" id="next-month">&rarr;</button>
                </div>

                <div class="jp-calendar-grid">
                    <div class="jp-cal-day-header">Sun</div>
                    <div class="jp-cal-day-header">Mon</div>
                    <div class="jp-cal-day-header">Tue</div>
                    <div class="jp-cal-day-header">Wed</div>
                    <div class="jp-cal-day-header">Thu</div>
                    <div class="jp-cal-day-header">Fri</div>
                    <div class="jp-cal-day-header">Sat</div>

                    <!-- Calendar days will be generated by JS -->
                    <div id="calendar-days"></div>
                </div>

            </div>

            <!-- Time Slots Section -->
            <div class="jp-scheduler-times">

                <div class="jp-selected-date">
                    <strong><?php esc_html_e('Selected Date:', 'jobportal'); ?></strong>
                    <span id="selected-date-display"><?php esc_html_e('Select a date', 'jobportal'); ?></span>
                </div>

                <div class="jp-timezone-selector">
                    <label><?php esc_html_e('Timezone:', 'jobportal'); ?></label>
                    <select id="timezone" class="jp-select">
                        <option value="PST">Pacific Time (PST)</option>
                        <option value="MST">Mountain Time (MST)</option>
                        <option value="CST">Central Time (CST)</option>
                        <option value="EST">Eastern Time (EST)</option>
                    </select>
                </div>

                <div class="jp-time-slots-container">
                    <h4><?php esc_html_e('Available Time Slots', 'jobportal'); ?></h4>

                    <div class="jp-time-period">
                        <div class="jp-period-label"><?php esc_html_e('Morning', 'jobportal'); ?></div>
                        <div class="jp-time-slots" id="morning-slots">
                            <button class="jp-time-slot" data-time="09:00">9:00 AM</button>
                            <button class="jp-time-slot" data-time="09:30">9:30 AM</button>
                            <button class="jp-time-slot" data-time="10:00">10:00 AM</button>
                            <button class="jp-time-slot" data-time="10:30">10:30 AM</button>
                            <button class="jp-time-slot" data-time="11:00">11:00 AM</button>
                            <button class="jp-time-slot" data-time="11:30">11:30 AM</button>
                        </div>
                    </div>

                    <div class="jp-time-period">
                        <div class="jp-period-label"><?php esc_html_e('Afternoon', 'jobportal'); ?></div>
                        <div class="jp-time-slots" id="afternoon-slots">
                            <button class="jp-time-slot" data-time="12:00">12:00 PM</button>
                            <button class="jp-time-slot" data-time="12:30">12:30 PM</button>
                            <button class="jp-time-slot" data-time="13:00">1:00 PM</button>
                            <button class="jp-time-slot" data-time="13:30">1:30 PM</button>
                            <button class="jp-time-slot" data-time="14:00">2:00 PM</button>
                            <button class="jp-time-slot" data-time="14:30">2:30 PM</button>
                            <button class="jp-time-slot" data-time="15:00">3:00 PM</button>
                            <button class="jp-time-slot" data-time="15:30">3:30 PM</button>
                        </div>
                    </div>

                    <div class="jp-time-period">
                        <div class="jp-period-label"><?php esc_html_e('Evening', 'jobportal'); ?></div>
                        <div class="jp-time-slots" id="evening-slots">
                            <button class="jp-time-slot" data-time="16:00">4:00 PM</button>
                            <button class="jp-time-slot" data-time="16:30">4:30 PM</button>
                            <button class="jp-time-slot" data-time="17:00">5:00 PM</button>
                            <button class="jp-time-slot" data-time="17:30">5:30 PM</button>
                        </div>
                    </div>

                </div>

            </div>

        </div>

        <!-- Interview Details Form -->
        <div class="jp-interview-details" id="interview-details" style="display: none;">

            <h3><?php esc_html_e('Interview Details', 'jobportal'); ?></h3>

            <div class="jp-details-summary">
                <div class="jp-summary-item">
                    <strong><?php esc_html_e('Date & Time:', 'jobportal'); ?></strong>
                    <span id="final-datetime"></span>
                </div>
                <div class="jp-summary-item">
                    <strong><?php esc_html_e('Duration:', 'jobportal'); ?></strong>
                    <span>45 minutes</span>
                </div>
            </div>

            <div class="jp-form-group">
                <label><?php esc_html_e('Interview Type', 'jobportal'); ?></label>
                <select id="interview-type" class="jp-select">
                    <option value="video"><?php esc_html_e('Video Call (Zoom)', 'jobportal'); ?></option>
                    <option value="phone"><?php esc_html_e('Phone Call', 'jobportal'); ?></option>
                    <option value="in-person"><?php esc_html_e('In-Person', 'jobportal'); ?></option>
                </select>
            </div>

            <div class="jp-form-group">
                <label><?php esc_html_e('Full Name', 'jobportal'); ?></label>
                <input type="text" id="candidate-name" class="jp-input" required>
            </div>

            <div class="jp-form-group">
                <label><?php esc_html_e('Email Address', 'jobportal'); ?></label>
                <input type="email" id="candidate-email" class="jp-input" required>
            </div>

            <div class="jp-form-group">
                <label><?php esc_html_e('Phone Number', 'jobportal'); ?></label>
                <input type="tel" id="candidate-phone" class="jp-input">
            </div>

            <div class="jp-form-group">
                <label><?php esc_html_e('Additional Notes (Optional)', 'jobportal'); ?></label>
                <textarea id="candidate-notes" class="jp-textarea" rows="3"></textarea>
            </div>

            <div class="jp-scheduler-actions">
                <button class="jp-btn jp-btn-outline" id="cancel-interview"><?php esc_html_e('Cancel', 'jobportal'); ?></button>
                <button class="jp-btn jp-btn-primary" id="confirm-interview"><?php esc_html_e('Confirm Interview', 'jobportal'); ?></button>
            </div>

        </div>

        <!-- Success Message -->
        <div class="jp-success-message" id="success-message" style="display: none;">
            <div class="jp-success-icon">✓</div>
            <h3><?php esc_html_e('Interview Scheduled Successfully!', 'jobportal'); ?></h3>
            <p><?php esc_html_e('A confirmation email has been sent to your inbox with the interview details and calendar invite.', 'jobportal'); ?></p>
            <button class="jp-btn jp-btn-primary" id="schedule-another"><?php esc_html_e('Schedule Another', 'jobportal'); ?></button>
        </div>

    </div>

    <style>
    .jp-interview-scheduler {
        max-width: 1200px;
        margin: 40px auto;
        padding: 40px;
        background: #fff;
        border-radius: 16px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.08);
    }

    .jp-scheduler-header {
        text-align: center;
        margin-bottom: 40px;
    }

    .jp-scheduler-header h2 {
        margin: 0 0 12px 0;
        color: #1e293b;
        font-size: 32px;
    }

    .jp-scheduler-header p {
        margin: 0;
        color: #64748b;
    }

    .jp-scheduler-container {
        display: grid;
        grid-template-columns: 1.2fr 1fr;
        gap: 40px;
        margin-bottom: 40px;
    }

    .jp-scheduler-calendar {
        background: #f8fafc;
        padding: 24px;
        border-radius: 12px;
    }

    .jp-calendar-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 24px;
    }

    .jp-calendar-header h3 {
        margin: 0;
        color: #1e293b;
        font-size: 20px;
    }

    .jp-cal-nav {
        width: 36px;
        height: 36px;
        border: none;
        background: #fff;
        border-radius: 8px;
        cursor: pointer;
        font-size: 18px;
        color: #4facfe;
        transition: all 0.2s;
    }

    .jp-cal-nav:hover {
        background: #4facfe;
        color: #fff;
    }

    .jp-calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 8px;
    }

    .jp-cal-day-header {
        text-align: center;
        padding: 12px;
        font-size: 12px;
        font-weight: 600;
        color: #64748b;
        text-transform: uppercase;
    }

    .jp-cal-day {
        aspect-ratio: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        background: #fff;
        border-radius: 8px;
        cursor: pointer;
        transition: all 0.2s;
        font-weight: 500;
        color: #1e293b;
    }

    .jp-cal-day:hover {
        background: #e0e7ff;
        color: #4facfe;
    }

    .jp-cal-day.selected {
        background: #4facfe;
        color: #fff;
    }

    .jp-cal-day.disabled {
        color: #cbd5e1;
        cursor: not-allowed;
    }

    .jp-cal-day.disabled:hover {
        background: #fff;
        color: #cbd5e1;
    }

    .jp-scheduler-times {
        background: #f8fafc;
        padding: 24px;
        border-radius: 12px;
    }

    .jp-selected-date {
        padding: 16px;
        background: #fff;
        border-radius: 8px;
        margin-bottom: 20px;
        color: #1e293b;
    }

    .jp-selected-date span {
        display: block;
        margin-top: 4px;
        color: #4facfe;
        font-weight: 600;
    }

    .jp-timezone-selector {
        margin-bottom: 24px;
    }

    .jp-timezone-selector label {
        display: block;
        margin-bottom: 8px;
        font-weight: 500;
        color: #1e293b;
    }

    .jp-select {
        width: 100%;
        padding: 10px 14px;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        background: #fff;
        cursor: pointer;
    }

    .jp-time-slots-container h4 {
        margin: 0 0 20px 0;
        color: #1e293b;
    }

    .jp-time-period {
        margin-bottom: 24px;
    }

    .jp-period-label {
        font-size: 12px;
        font-weight: 600;
        color: #64748b;
        text-transform: uppercase;
        margin-bottom: 12px;
        letter-spacing: 0.5px;
    }

    .jp-time-slots {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 8px;
    }

    .jp-time-slot {
        padding: 10px;
        background: #fff;
        border: 2px solid #e2e8f0;
        border-radius: 6px;
        font-size: 14px;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s;
        color: #475569;
    }

    .jp-time-slot:hover {
        border-color: #4facfe;
        background: #e0e7ff;
        color: #4facfe;
    }

    .jp-time-slot.selected {
        background: #4facfe;
        border-color: #4facfe;
        color: #fff;
    }

    .jp-time-slot.booked {
        background: #f1f5f9;
        border-color: #e2e8f0;
        color: #cbd5e1;
        cursor: not-allowed;
        text-decoration: line-through;
    }

    .jp-interview-details {
        background: #f8fafc;
        padding: 32px;
        border-radius: 12px;
        animation: slideIn 0.3s ease;
    }

    @keyframes slideIn {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .jp-interview-details h3 {
        margin: 0 0 24px 0;
        color: #1e293b;
    }

    .jp-details-summary {
        background: #fff;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 24px;
    }

    .jp-summary-item {
        padding: 12px 0;
        border-bottom: 1px solid #f1f5f9;
    }

    .jp-summary-item:last-child {
        border-bottom: none;
    }

    .jp-summary-item strong {
        display: block;
        margin-bottom: 4px;
        color: #64748b;
        font-size: 14px;
    }

    .jp-summary-item span {
        color: #1e293b;
        font-size: 16px;
    }

    .jp-form-group {
        margin-bottom: 20px;
    }

    .jp-form-group label {
        display: block;
        margin-bottom: 8px;
        font-weight: 500;
        color: #1e293b;
    }

    .jp-input, .jp-textarea {
        width: 100%;
        padding: 12px 16px;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        font-size: 14px;
    }

    .jp-input:focus, .jp-textarea:focus {
        outline: none;
        border-color: #4facfe;
        box-shadow: 0 0 0 3px rgba(79, 172, 254, 0.1);
    }

    .jp-scheduler-actions {
        display: flex;
        gap: 12px;
        margin-top: 24px;
    }

    .jp-btn {
        flex: 1;
        padding: 14px 28px;
        border-radius: 8px;
        font-weight: 600;
        cursor: pointer;
        border: none;
        transition: all 0.2s;
    }

    .jp-btn-primary {
        background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        color: #fff;
    }

    .jp-btn-primary:hover {
        transform: translateY(-2px);
        box-shadow: 0 8px 20px rgba(79, 172, 254, 0.3);
    }

    .jp-btn-outline {
        background: #fff;
        border: 2px solid #e2e8f0;
        color: #475569;
    }

    .jp-success-message {
        text-align: center;
        padding: 60px 40px;
        background: #f8fafc;
        border-radius: 12px;
        animation: fadeIn 0.5s ease;
    }

    @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }

    .jp-success-icon {
        width: 80px;
        height: 80px;
        margin: 0 auto 24px;
        background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        color: #fff;
        font-size: 48px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .jp-success-message h3 {
        margin: 0 0 16px 0;
        color: #1e293b;
    }

    .jp-success-message p {
        margin: 0 0 32px 0;
        color: #64748b;
    }

    @media (max-width: 1024px) {
        .jp-scheduler-container {
            grid-template-columns: 1fr;
        }

        .jp-time-slots {
            grid-template-columns: repeat(2, 1fr);
        }
    }
    </style>

    <script>
    (function() {
        let selectedDate = null;
        let selectedTime = null;

        // Simple calendar generation
        const calendarDays = document.getElementById('calendar-days');
        const currentDate = new Date();
        const daysInMonth = 31; // Simplified for demo

        for (let i = 1; i <= daysInMonth; i++) {
            const dayBtn = document.createElement('button');
            dayBtn.className = 'jp-cal-day';
            if (i < currentDate.getDate()) {
                dayBtn.className += ' disabled';
            }
            dayBtn.textContent = i;
            dayBtn.addEventListener('click', function() {
                if (!this.classList.contains('disabled')) {
                    document.querySelectorAll('.jp-cal-day').forEach(d => d.classList.remove('selected'));
                    this.classList.add('selected');
                    selectedDate = `March ${i}, 2024`;
                    document.getElementById('selected-date-display').textContent = selectedDate;
                }
            });
            calendarDays.appendChild(dayBtn);
        }

        // Time slot selection
        document.querySelectorAll('.jp-time-slot').forEach(slot => {
            slot.addEventListener('click', function() {
                if (!this.classList.contains('booked') && selectedDate) {
                    document.querySelectorAll('.jp-time-slot').forEach(s => s.classList.remove('selected'));
                    this.classList.add('selected');
                    selectedTime = this.dataset.time;

                    // Show details form
                    document.getElementById('final-datetime').textContent = `${selectedDate} at ${this.textContent}`;
                    document.getElementById('interview-details').style.display = 'block';
                    document.getElementById('interview-details').scrollIntoView({ behavior: 'smooth' });
                }
            });
        });

        // Cancel button
        document.getElementById('cancel-interview').addEventListener('click', function() {
            document.getElementById('interview-details').style.display = 'none';
            document.querySelectorAll('.jp-time-slot').forEach(s => s.classList.remove('selected'));
            selectedTime = null;
        });

        // Confirm interview
        document.getElementById('confirm-interview').addEventListener('click', function() {
            const name = document.getElementById('candidate-name').value;
            const email = document.getElementById('candidate-email').value;

            if (name && email) {
                document.getElementById('interview-details').style.display = 'none';
                document.getElementById('success-message').style.display = 'block';
                document.getElementById('success-message').scrollIntoView({ behavior: 'smooth' });
            } else {
                alert('Please fill in all required fields.');
            }
        });

        // Schedule another
        document.getElementById('schedule-another').addEventListener('click', function() {
            location.reload();
        });

    })();
    </script>
    <?php
    return ob_get_clean();
}
add_shortcode('jobportal_interview_scheduler', 'jobportal_interview_scheduler_shortcode');
